# Generated by Django 3.1.13 on 2022-05-21 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='imagen',
            field=models.ImageField(default=1, upload_to='images'),
            preserve_default=False,
        ),
    ]
