from ast import Index
from cgi import test
from django.urls import path
from .views import (aTienda, adminPdcto, administrador1, agInventario, agReceta, busqueda, busqueda_cate, comprador, comprador_register, 
crearPerfil, editInventario, editarReceta, eliminarDelInventario, eliminarMsj, eliminarReceta, eliminarUsuario, empPedidos, 
emprendedor_register, editarPdcto, eliminarPdcto, emprendedor, empPublico, 
index, ingPdcto, inventario, login_request, logout_view, producto, recetas, regCompras, register,
editarPerfilEmp, reporte, verReceta
)

urlpatterns = [
    path('', index, name="index"),
    # path('', Index.as_view(), name="index"),
    path('login/', login_request, name="login"),
    path('logout/', logout_view, name='logout'),
    path('register/', register, name="register"),
    path('comprador_register/', comprador_register.as_view(), name="comprador_register"),
    path('emprendedor_register/', emprendedor_register.as_view(), name="emprendedor_register"),
    path('producto/<id>/', producto, name="producto"),
    path('emprendedor/', emprendedor, name="emprendedor"),
    path('comprador/', comprador, name="comprador"),
    path('administrador1/', administrador1, name="administrador1"),
    path('ingPdcto/', ingPdcto, name="ingPdcto"),
    path('regCompras', regCompras, name="regCompras"),
    path('busqueda/', busqueda, name="busqueda"),
    path('busqueda_cate/<id>', busqueda_cate, name="busqueda_cate"),
    path('empPublico/', empPublico, name="empPublico"),
    path('empPedidos/', empPedidos, name="empPedidos"),
    path('adminPdcto/', adminPdcto, name="adminPdcto"),
    path('editarPdcto/<id>/', editarPdcto, name="editarPdcto"),
    path('eliminarPdcto/<id>/', eliminarPdcto, name="eliminarPdcto"),
    path('eliminarUsuario/<id>/', eliminarUsuario, name="eliminarUsuario"),
    path('eliminarMsj/<id>/', eliminarMsj, name="eliminarMsj"),
    path('eliminarDelInventario/<id>/', eliminarDelInventario, name="eliminarDelInventario"),
    path('eliminarReceta/<id>/', eliminarReceta, name="eliminarReceta"),
    path('editarPerfilEmp/<id>/', editarPerfilEmp, name="editarPerfilEmp"),
    path('crearPerfil/', crearPerfil, name="crearPerfil"),
    path('aTienda/<id>/', aTienda, name="aTienda"),
    path('inventario/', inventario, name="inventario"),
    path('agInventario/', agInventario, name="agInventario"),
    path('editInventario/<id>/', editInventario, name="editInventario"),
    path('recetas/', recetas, name="recetas"),
    path('agReceta/', agReceta, name="agReceta"),
    path('verReceta/<id>/', verReceta, name="verReceta"),
    path('editarReceta/<id>/', editarReceta, name="editarReceta"),
    path('reporte/<id>/', reporte, name="reporte"),
]