version: '3.7'

services:
  database:
    image: postgres 
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=prender-db

volumes:
  postgres_data:
    driver: local